"""Google Ads audience sync — creates a Rule-Based User List from topic keywords.

Authentication uses a short-lived OAuth2 access token (GOOGLE_ADS_ACCESS_TOKEN).
In production replace this with a service account refresh-token flow.

API reference:
  https://developers.google.com/google-ads/api/rest/reference/rest/v17/customers.userLists/mutate

Retry policy: up to 3 attempts with exponential back-off on HTTP 429.
Platform errors (4xx except 429, 5xx) are raised immediately so the DAG task
can log them to audience_sync_log without retrying invalid payloads.
"""

from __future__ import annotations

import logging
import os
import time

import requests

from integrations.audience_mapper import AudienceSpec

logger = logging.getLogger(__name__)

_API_BASE = "https://googleads.googleapis.com/v17"
_MAX_KEYWORDS = 20          # Google Ads userList URL-rule item limit per group
_MEMBERSHIP_LIFE_SPAN = 30  # days
_RETRY_DELAYS = (1.0, 2.0, 4.0)


class GoogleAdsAudienceSync:
    """Push a keyword-based User List to Google Ads for the given Golden Record."""

    def __init__(self) -> None:
        self._customer_id = os.environ.get("GOOGLE_ADS_CUSTOMER_ID", "").replace("-", "")
        self._developer_token = os.environ.get("GOOGLE_ADS_DEVELOPER_TOKEN", "")
        self._access_token = os.environ.get("GOOGLE_ADS_ACCESS_TOKEN", "")
        self._enabled = os.environ.get("GOOGLE_ADS_ENABLED", "true").lower() == "true"

    # ── Public API ─────────────────────────────────────────────────────────────

    def sync(self, golden_record_id: str, spec: AudienceSpec) -> str | None:
        """Create a Google Ads User List for the given AudienceSpec.

        Returns:
            audience_id (resourceName string) on success.
            None if the integration is disabled via GOOGLE_ADS_ENABLED=false.

        Raises:
            RuntimeError: missing configuration.
            requests.HTTPError: non-retryable API error.
        """
        if not self._enabled:
            logger.info(
                "Google Ads sync disabled — skipping golden_record_id=%s", golden_record_id
            )
            return None

        self._assert_configured()

        payload = self._build_payload(golden_record_id, spec)
        data = self._post_with_retry(
            f"{_API_BASE}/customers/{self._customer_id}/userLists:mutate",
            payload,
        )

        # Response shape: {"results": [{"resourceName": "customers/.../userLists/..."}]}
        resource_name: str = (data.get("results") or [{}])[0].get("resourceName", "")
        logger.info(
            "Google Ads user list created: golden_record_id=%s resource_name=%s",
            golden_record_id,
            resource_name,
        )
        return resource_name

    # ── Private helpers ────────────────────────────────────────────────────────

    def _assert_configured(self) -> None:
        missing = [
            name
            for name, val in (
                ("GOOGLE_ADS_CUSTOMER_ID", self._customer_id),
                ("GOOGLE_ADS_DEVELOPER_TOKEN", self._developer_token),
                ("GOOGLE_ADS_ACCESS_TOKEN", self._access_token),
            )
            if not val
        ]
        if missing:
            raise RuntimeError(
                f"Google Ads sync requires env vars: {', '.join(missing)}"
            )

    def _build_payload(self, golden_record_id: str, spec: AudienceSpec) -> dict:
        # Truncate cluster name so the audience name stays within the 255-char limit
        audience_name = (
            f"trend-arb-{spec.topic_cluster[:40]}-{golden_record_id[:8]}"
        )
        keywords = spec.keywords[:_MAX_KEYWORDS]

        return {
            "operations": [
                {
                    "create": {
                        "name": audience_name,
                        "description": (
                            f"Auto-generated by Trend Arbitrage — cluster: {spec.topic_cluster}"
                        ),
                        "membershipLifeSpan": _MEMBERSHIP_LIFE_SPAN,
                        "ruleBasedUserList": {
                            "flexibleRuleUserList": {
                                "inclusiveRuleOperator": "OR",
                                "inclusiveOperands": [
                                    {
                                        "rule": {
                                            "ruleItemGroups": [
                                                {
                                                    "ruleItems": [
                                                        {
                                                            "urlRuleItem": {
                                                                "operator": "URL_CONTAINS",
                                                                "value": kw,
                                                            }
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    }
                                    for kw in keywords
                                ],
                            }
                        },
                    }
                }
            ]
        }

    def _post_with_retry(self, url: str, payload: dict) -> dict:
        headers = {
            "Authorization": f"Bearer {self._access_token}",
            "developer-token": self._developer_token,
            "Content-Type": "application/json",
        }
        last_exc: Exception | None = None
        for attempt, delay in enumerate(_RETRY_DELAYS):
            try:
                resp = requests.post(url, json=payload, headers=headers, timeout=15)
            except requests.RequestException as exc:
                last_exc = exc
                if attempt < len(_RETRY_DELAYS) - 1:
                    time.sleep(delay)
                    continue
                raise

            if resp.status_code == 429:
                retry_after = float(resp.headers.get("Retry-After", delay))
                if attempt < len(_RETRY_DELAYS) - 1:
                    time.sleep(retry_after)
                    continue
            resp.raise_for_status()
            return resp.json()

        if last_exc:
            raise last_exc
        return {}
